cmu-delphi/signal_documentation

Dockerfile, docker-compose.yaml
This now works to run the project locally for me. We should have Brian and Minh attempt to run this as well.
=> created Ubuntu docker container that works on linux now

.ci.env, .env.example, .github/workflows/build-and-deploy.yaml, Dockerfile, Pipfile, README.md, docker-compose.yaml, nginx/default.conf.template
This PR ultimately adds necessities needed to start deploying the application. More specific information can be found in each commit, but a synopsis is:
- Adds necessities to build and deploy containers via GH Actions
- Enhances `docker-compose.yml` to help the above
- Integrates an Nginx container and static file/proxy config for staging/production use
- Slight package and `pipenv` addition to the container Dockerfile
- Readme updates
=> Prepares this application for deployment

.github/workflows/generate-sphynx-docs.yml
🛠️ .github/workflows/generate-sphynx-docs.yml -> Updated trigger branch to develop
=> github/workflows/generate-sphynx-docs.yml -> Updated trigger branch to develop

src/assets/css/style.css, src/signals/filters.py, src/signals/forms.py, src/signals/views.py, src/templates/signals/signals.html, src/templates/signals/signals_list.html
🛠️ signals/filters.py -> Added NumberInFilter and id field to SignalFilter
🛠️ signals/forms.py -> Added id field to SignalFilterForm 🛠️ signals/views.py -> Added "id" to get_url_params method 🛠️ signals.html -> Added id field and filter-submit button 🛠️ signals_list.html -> Added checkbox for id and associated form handling
=> Added filters by several ID to perform more precise filtering 

src/signals/views.py, src/templates/signals/signals.html
Removed "check" filters by default.
Collapse filters if there are too many of them, but show if any of them are checked.
Added button to show/hide filter options.
=> OKRS24-118 Update filters

src/templates/signals/signals.html
Added checkbox to 'Select all/Clear all' filters
=> OKRS24-119

src/templates/signals/signals.html
🛠️ signals.html -> Modified row layout and added export button.
=> Added link to COVIDcast EXPORT page 

src/templates/signals/signals.html
🛠️ signals.html -> Updated form submission to use 'filters-form' ID.
=> Fixed Sort By submit function

src/templates/signals/signals.html
signals.html -> Updated export button with new links and target attributes.
=> Added link to EpiVis interactive tool

src/templates/signals/signals.html
🛠️ signals.html -> Updated the HTML structure to use accordion for a better user experience. Added modal popups for detailed information on Pathogen, Active, Available Geography, Signal Type, Category, Format Type, Source, and Time Label.
=> Filters made collapsible

src/signals/tools.py, src/templates/signals/signals.html
- Added 'x' to the search bar
- Made accordions not collapsed if filters are selected
=> Okrs24 159 add x to cancel search and clear search bar

src/templates/index.html
🛠️ index.html -> Updated About Us dropdown link
=> Updated 'About Us' dropdown link

src/templates/signals/signals.html
🛠️ signals.html -> Added "Active" column
🛠️ signals.html -> Added conditional formatting for "Active" column
=> Added "Active" column to the signals list view

src/templates/index.html
🛠️ index.html -> Modified navigation links for signals and datasources.
=> Higth light navigation links `signals` and `datasources` if they are active.

src/templates/signals/signals.html
🛠️ signals.html -> Updated layout and alignment for export and chart buttons. Updated input group layout for sorting.
=> Commented out export and chart buttons and changed sorting position

src/templates/signals/signals.html
Make signal list table responsive
=> OKRS24-164

src/assets/css/custom.css, src/templates/index.html, src/templates/signals/signals.html
=> OKRS24-165

src/templates/signals/signals.html
Added tooltip to the search field.
=> OKRS24-206

src/signals/forms.py
🛠️ forms.py -> Modified source field to use MultipleChoiceField with custom choices.
=> changed source to show external_name in filter

src/signals/filters.py, src/signals/forms.py, src/signals/views.py
🛠️ views.py -> Modified source field processing
🛠️ forms.py -> Updated source field choices
=> OKRS24-220 fixed datasources duplication, chanded filter from id to external_name value with in lookup

src/signals/forms.py
Fixed 'SourceSubdivision' table does not exist on the fresh database.
=> OKRS24-224 

.github/workflows/build-and-deploy.yaml
Will run CI on `main` branch changes and build container images tagged with `:latest`.
=> Enable CI on main branch
