cmu-delphi/signal_documentation

src/signal_documentation/urls.py
The changes made in this PR include:
- Modified `src/signal_documentation/urls.py` to handle the case when `settings.MAIN_PAGE` is empty.
- Added a conditional statement to include the `signals.urls` when `settings.MAIN_PAGE` is not empty.
- This change ensures that the `signals.urls` is included in the URL patterns only when `settings.MAIN_PAGE` is not empty.
=> SD-30 Leaving `MAIN_PAGE` unset causes errors

src/signal_documentation/urls.py
Right now we see this when checking out admin page. This PR makes admin site available at the correct address.
=> Make admin site available

src/signal_documentation/settings.py
We will need to be able to set `CSRF_TRUSTED_ORIGINS`. This PR enables passing in values from the environment at runtime.
=> Enables passing in values via 'CSRF_TRUSTED_ORIGINS'

src/templates/index.html, src/templates/signals/signals_list.html
Before this fix, infinite scroll didn't preserve any filters, so kept loading all records despite filters.
=> Fixed infinite scroll

Pipfile
It looks like this package went missing at some point, and the most recent staging container build was failing because of it. Adding it back in!
=> Add gunicorn package

src/signals/forms.py, src/signals/models.py, src/signals/views.py
- Add a checkbox for whether to show all signals, only historical, or only current
- Default to checking both boxes (both historical and current)
=> OKRS24-92 Change 'Active' filter

src/assets/css/style.css, src/signals/admin.py, src/signals/filters.py, src/signals/forms.py, src/signals/views.py, src/templates/signals/signal_detail.html, src/templates/signals/signals.html
Okrs24 100 Convert dropdowns do checkboxes
=> Okrs24 100 Convert dropdowns do checkboxes

src/base/models.py, src/templates/signals/signal_detail.html
Update 'Related Links' section.
Handle non-200 status codes
=> OKRS24-117 

Pipfile, Pipfile.lock, setup.cfg, src/base/context_processors.py, src/base/models.py, src/datasources/models.py, src/docs/source/conf.py, src/signal_documentation/settings.py, src/signals/filters.py, src/signals/forms.py, src/signals/models.py, src/signals/tools.py, src/signals/views.py
🛠️ models.py -> Updated field types and help texts for models
🛠️ conf.py -> Updated templates_path and html_static_path
🛠️ models.py -> Updated return statements
🛠️ conf.py -> Updated templates_path and exclude_patterns
🛠️ filters.py -> Modified query assignment
🛠️ forms.py -> Modified __init__ method
🛠️ tools.py -> Modified format_date method
🛠️ views.py -> Modified paginate_by and get_queryset
🛠️ Pipfile.lock -> Updated package versions
🛠️ settings.py -> Updated PAGE_SIZE to be an integer
🛠️ views.py -> Updated get_template_names method to check for htmx attribute
=> Okrs24 138 fix mypy issues

src/signal_documentation/settings.py, src/templates/signals/signal_detail.html
Make pathogen, geography and signal type tags clickable.
=> OKRS24-170

src/signals/filters.py, src/signals/forms.py, src/signals/views.py, src/templates/signals/signals.html
🛠️ forms.py -> Updated time_label to time_type
🛠️ views.py -> Updated time_label to time_type
🛠️ signals.html -> Updated time_label to time_type
🛠️ filters.py -> Updated time_label to time_type
=> OKRS24-185 Change 'time_label' to use `time_type` field

src/fixtures/nation.json, src/templates/signals/epivis_export_data_block.html
Added missing 'nation' geo value to plot/export data section.
=> OKRS24-204

src/signal_documentation/settings.py, src/signals/filters.py, src/signals/forms.py, src/signals/views.py, src/templates/signals/signals.html
🛠️ src/signals/filters.py -> Added base_signal filter
🛠️ src/signals/forms.py -> Added base_signal field
🛠️ src/signals/views.py -> Added base_signal to URL params
🛠️ src/templates/signals/signals.html -> Added base_signal accordion
=> Added filter by base_for field

src/templates/signals/data_visualization_export.html, src/templates/signals/signal_detail.html
Fixed data preview feature. Now it user choose params to generate preview link instead of getting that link from the database.
=> OKRS24-107

.github/workflows/build-and-deploy.yaml, README.md
We would like start working with three primary branches that map simply to the current development, review, and release process for this application.
This PR updates our CI process to build images from these branches, and adds some small updates to the README to describe the way these branches should be used.
=> Update CI build process

src/signal_documentation/settings.py, src/signals/tasks.py, src/signals/views.py, src/templates/signals/data_visualization_export.html
`api.delphi.cmu.edu` is the preferred hostname
=> use api.delphi.cmu.edu instead of api.covidcast

src/signal_documentation/settings.py, src/signals/serializers.py, src/signals/urls.py, src/signals/views.py
In order to speed up signal list load, added caching.
Set cache time to 24 hours as most of our data is kinda "static" so caching time can be set to some higher value.
=> OKRS24-235 Added caching.

src/base/management/commands/initadmin.py
Added custom command to create admin user.
Username, user email and user password are taken from env vars (or default values.).
To run command execute `python manage.py initadmin`
=> Added custom createsuperuser command

.github/workflows/build-and-deploy.yaml, src/signal_documentation/settings.py
This is a slight refactor to mimic the way we have configured the Sentry SDK in delphi-epidata. It mostly addresses an issue in which the "debug" var was not being set properly and always defaulted to `True`, causing a _ton_ of extra logging.
=> Update Sentry SDK config

.github/workflows/build-and-deploy.yaml, nginx/default.conf.template
There are two URL types used for looking up static files:
- http://MAIN_PAGE/static
- http://MAIN_PAGE/static/assets
We don't collect static files for both locations, so this updates our Nginx config to use the same alias for both URL types. We do this by adding an additional location for `/static/assets` and then pointing it the same alias we use for `/static`.
=> Update static file serving config in Nginx
